### ISSUE TITLE
New event feed for bay.lgbt

### ISSUE THREAD

**Issue by taoketao** [queeragenda/bay.lgbt#10]
Hi Ivy! I'm new to submitting events to bay.lgbt so I hope I did it right.

Public calendar links:
https://calendar.google.com/calendar/embed?src=22a5ba4763901dfd77acb464e867b158e182c1608594118e53c0c0cb10f07aa9%40group.calendar.google.com&ctz=America%2FLos_Angeles
22a5ba4763901dfd77acb464e867b158e182c1608594118e53c0c0cb10f07aa9@group.calendar.google.com

I set up the API key. I'm a former software developer so I think I got it right, but I'm happy to fix issues! And if that doesn't work, here's the instagram flyer link followed by alt text. Thanks so much! ~Morgan. 

https://www.instagram.com/p/CzrCSuNLZZ4/

Event text:

Introducing PIT STOP, SF’s new fem4fem dance party! Swap your tires halfway between Mother and Jolene’s at Slate SF for a reclaimed NASCAR-themed Friday after Thanksgiving!

Beats by our wheel spinners [@radiarends](https://www.instagram.com/radiarends/), [@discnogirl](https://www.instagram.com/discnogirl/), [@tom_marsi](https://www.instagram.com/tom_marsi/), and [@cntentwarning](https://www.instagram.com/cntentwarning/). Credits to collaborators and co-hosts [@lucy.lapin](https://www.instagram.com/lucy.lapin/), [@radiarends](https://www.instagram.com/radiarends/), [@theageofsin](https://www.instagram.com/theageofsin/) 

Live music from 9pm-2am, 21+, 11/24. Non-femmes are welcome in this femme-first space.

**Comment by lily-mara** [comment]
Hi @taoketao, thanks for your patience on this issue. I'm helping Ivy out with the maintenance of bay.lgbt. Are you still interested in having this calendar added to bay.lgbt? I notice that there are no events on the calendar and the Instagram post you provided appears to be deleted. Happy to add the calendar if you're still running great events 💖

**Comment by lily-mara** [comment]
Thanks Morgan, I'm sorry we weren't able to host your events when they were still going on. Hope you're well 💖
