### ISSUE TITLE
Queer Pinball Event Feed for Calendar

### ISSUE THREAD

**Issue by JackieTr4n** [queeragenda/bay.lgbt#11]
Hello! I would love to add The San Francisco Queer Pinball League's 4th season to the calendar. I created a public calendar here: 

https://calendar.google.com/calendar/u/1?cid=MGJlYWQ4NTYzYzFjMDQ3MjFkZjk5MzYwN2ZkYjhhZmI5M2NjYmI2ZjRlYjU2ZjdmZmQzYzczZjU0ZGM5NGY2NkBncm91cC5jYWxlbmRhci5nb29nbGUuY29t

A link to our website: http://www.sfqpl.com

And our event text:
The San Francisco Queer Pinball League RETURNS for our 4th season with 3 awesome locations! 

Gestalt SF, Emporium SF, and The Detour SF

League nights will be every Tuesday at these rotating venues from June 18th - August 20th at 7pm. Each night we will play 5 rounds of Group MatchPlay, with an A/B division finals on August 27th. No commitment is required and everyone will qualify for finals night for cash, trophies, and other awesome prizes!

SFQPL is a queer pinball league based in San Francisco for LGBTQIA+ players and their allies! We are a beginner focused league that strives to get new players into the game. Come learn basic strategy or advanced skills... How to score big points on different machines... Heck! Maybe even teach us a thing or two! All skill levels are welcome!

Membership dues are $5 per night, or $35 for the whole season. 
Come grab a drink, and flip with your new queer friends! 😜🏳️‍🌈

C U Next Tuesday!

Please let me know if you need anything else. Email: thejackieopal@gmail.com

**Comment by bytewife** [comment]
Hi Jackie! I'll add this when I can- I have a lot of fixing to do for this site but I've not had time recently :/  Thanks for the calendar!

**Comment by JackieTr4n** [comment]
Thank you and no worries! 😊

**Comment by lily-mara** [comment]
Hi Jackie 👋 I added the SFQPL in [a80175e](https://github.com/queeragenda/bay.lgbt/commit/a80175ed1ace273b3cee05e1fb89b08e72d93ca1), your events should start showing up after we deploy the new version of bay.lgbt tomorrow. Thank you for your patience!

**Comment by JackieTr4n** [comment]
Thank you!!
